baseURL: https://jacklgreenberg.com
languageCode: en-us
title: Jack Greenberg

params:
  name: Jack Greenberg
  email: j@jacklgreenberg.com
  subtitle: Electrical and Firmware Engineer

markup:
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines:
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    style: dracula
    tabWidth: 4
  goldmark:
    extensions:
      footnote: true

outputs:
  page:
    - json
    - html

privacy:
  youtube:
    privacyenhanced: true
